### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by jackwilsdon** [open-health-hub/clinical_calculator_api#1]
- [x] Implement msoaobesity calculator
- [ ] Complete [clinical_calculator_frontend](http://github.com/open-health-hub/clinical_calculator_frontend)
- [ ] Tidy up codebase
  - [x] Work out a better way of subclassing [CalculatorLoader](https://github.com/open-health-hub/clinical_calculator_api/blob/master/lib/calculator_loader.rb) and [HelperLoader](https://github.com/open-health-hub/clinical_calculator_api/blob/master/lib/helper_loader.rb), as they both implement some of the same functionality
  - [ ] Make parentheses usage consistent 
- [x] Change file names to use snake case (`calculatorloader.rb` -> `calculator_loader.rb`)
- [ ] Write unit tests
  - [ ] Add `.travis.yml` for Travis CI
- [x] Fix all RuboCop offences
- [ ] Create example calculator code
  - [ ] Fix grammar and spelling
- [ ] Create docker container with management tools
- [ ] Add an analytics platform (see [Tyk](https://tyk.io/))
- [ ] Find a better way to handle `not_found`
  - Possibly abstract `response` generation to it's own method
- [ ] Add configuration file
- [ ] Add versioning to system
- [ ] Add API versioning to calculators
- [ ] Add documentation endpoint
  - [ ] Add documentation method to [CalculatorContext](https://github.com/open-health-hub/clinical_calculator_api/blob/master/lib/calculator_context.rb), allowing request fields to be documented
  - [ ] Add special documentation endpoint to access documentation for different endpoints
- [ ] Implement QRISK2 calculation (C implementation can be found [here](http://www.qrisk.org/index.php#software))
- [ ] Document calculator API and syntax
- [ ] Write RDoc comments for classes
- [ ] Update calculator style

``` ruby
class MyCalculator < Calculator
 def initialize
   # Set up all of your stuff here (e.g. load JSON files)
 end

 # Endpoints are named the same as their method unless otherwise specified
 #
 # GET /first
 def my_first_endpoint
   return "Hello, this is the first endpoint!"
 end

 # GET /my_second_endpoint
 def my_second_endpoint
   return "Hello, this is the second endpoint!"
 end

 endpoint :my_first_endpoint, name: :first
 endpoint :my_second_endpoint # Name is not required
end
```

**Comment by pacharanero** [comment]
closing this old issue as we have now transitioned to a Rails version and much of this issue is no longer relevant
